name: tinder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # fluttery: ^0.0.8
  fluttery_dart2: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
    - assets/14.jpg
    - assets/15.jpg
    - assets/16.jpg
    - assets/17.jpg
    - assets/18.jpg
    - assets/19.jpg
