name: tinder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  tflite: 1.0.4
  flutter_text_to_speech: ^3.0.6
  flutter_tts: ^0.6.0
  # fluttery: ^0.0.8
  fluttery_dart2: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/11.jpg
    - assets/12.jpg
    - assets/13.jpg
